### ISSUE TITLE
Conflicts regarding the violation of GPL3 and MIT License.

### ISSUE THREAD

**Issue by janicez** [raccoon-ircd/raccoon#2]
>Closing this issue, it's on github and can be forked. Yet crying about it!
>
>Veronika get out of here you cretin

_Originally posted by @TwinUsers in https://github.com/raccoon-ircd/raccoon/issues/1#issuecomment-787201047_

I have no problem with IRCa being forked and even used for commercial use, as long as appropriate authorship declarations are made. But eviscerating the credits from source and binary versions, as well as from the Git commit log, as incompletely detailed in the since-removed "irrelevant" comment, is wholly inappropriate, and by doing so, you violate the GPL version 3 as well as the MIT license, which some parts of the software are licensed under.

**Comment by ghost** [comment]
@janicez I have no personal interest to fork down your repository. The inner documentation files constitute from our Former IRCd -ircd-nine which was the ChatD, the proper maintainance rights of which were granted to us by its Former Owner i.e You. They have no relation with IRCa. As for the code, I am willing to give you credits in the README.md file , but the CREDITS file is not coming back.

I will be adding the CREDITS to the Ratbox Team, Hybrid Team, Charybdis Team, AsterIRC Team with launching the Security Updates and Bug Fixes to some abnormally working modules of the Daemon.

**Comment by ghost** [comment]
Try to be professional while adding Titles in your Issues you open in future.
Closing this issue.
